enum ApiErrorEnum {
  RESOURCE_NOT_FOUND_ERROR = 'RESOURCE_NOT_FOUND_ERROR',
  SECURITY_ERROR = 'SECURITY_ERROR',
  SERVER_ERROR = 'SERVER_ERROR',
  SERVER_UNREACHABLE = 'SERVER_UNREACHABLE',
  CONN_ABORTED = 'ECONNABORTED',
}

export default ApiErrorEnum;
