export enum PrefrenceKeyEnum {
  COUNTRY_DETAIL = 'countryDetails',
  LABELS = 'labels',
  STATUS = 'status',
  ACTIVITY_TYPE = 'activityType',
  TASK_TYPE = 'taskType',
  LEAD_FORM = 'customForm',
  LEAD_DUPLICATE_FLAG = 'isDuplicateLeadAllow',
  PERMISSIONS = 'permissions',
  FILE_TAG = 'fileTags',
  MESSAGE_TAG = 'messageTags',
  PAGE_TAG = 'pageTags',
  TAX_OPTIONS = 'taxes',
  LEAD_CUSTOM_SOURCES = 'customSource',
  ACTIVITY_NOTIFICATION_FLAG = 'activityNotification',
  NEWLEAD_NOTIFICATION_FLAG = 'newLeadNotification',
  RECENT_NOTIFICATION_FLAG = 'recentActivityNotification',
  SCREEN_PERMISSION = 'screenPermission',
}
